name: Fetch Latest YouTube Video
on:
  schedule:
    - cron: '0 * * * *' # Roda a cada hora
  workflow_dispatch: # Permite execução manual

jobs:
  fetch-latest-video:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install feedparser

      - name: Fetch and process YouTube feed
        run: |
          python -c "
import feedparser

# URL do feed do YouTube
feed_url = 'https://www.youtube.com/feeds/videos.xml?channel_id=UCWl8Ma619mTTXoo9P7mASdQ'
feed = feedparser.parse(feed_url)

# Encontrar o vídeo mais recente que não é short
latest_video = None
for entry in feed.entries:
    # Verifica se é um vídeo (não short) pelo link
    if 'youtu.be' not in entry.link and 'watch' in entry.link:
        latest_video = entry.link
        break

# Salvar apenas o link no arquivo .js
if latest_video:
    with open('latest_video.js', 'w') as f:
        f.write(f'\"{latest_video}\"')
"
      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add latest_video.js
          git commit -m 'Update latest YouTube video link' || echo "No changes to commit"
          git push
