name: Update YouTube Video Link

on:
  schedule:
    - cron: '0 * * * *'  # A cada hora
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Run Python script
        run: python update_video.py

      - name: Commit changes
        if: success() || failure() && steps.run_python.outcome != 'success'  # roda só se houve mudança
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add latestVideo.js
          git diff --cached --quiet || git commit -m "Atualiza link do vídeo mais recente"
          git push
