name: Update Latest YouTube Video URL

     on:
       schedule:
         - cron: '0 * * * *' # Executa a cada hora, no minuto 0
       workflow_dispatch: # Permite execução manual

     jobs:
       update-video:
         runs-on: ubuntu-latest
         permissions:
           contents: write # Permissão para commitar alterações

         steps:
           - name: Checkout repository
             uses: actions/checkout@v4

           - name: Set up Python
             uses: actions/setup-python@v5
             with:
               python-version: '3.11'

           - name: Install dependencies
             run: |
               python -m pip install --upgrade pip
               pip install -r requirements.txt

           - name: Create or update latest-video.js
             run: |
               python .github/scripts/fetch_latest_video.py
             env:
               CHANNEL_ID: UCWl8Ma619mTTXoo9P7mASdQ

           - name: Commit changes
             run: |
               git config user.name "GitHub Action"
               git config user.email "action@github.com"
               git add latest-video.js
               git diff --quiet && git diff --staged --quiet || (git commit -m "Atualiza URL do vídeo mais recente do YouTube" && git push)
