name: Update Latest YouTube Video URL

     on:
       schedule:
         - cron: '0 * * * *' # Executa a cada hora, no minuto 0
       workflow_dispatch: # Permite execução manual

     jobs:
       update-video:
         runs-on: ubuntu-latest
         permissions:
           contents: write # Permissão para commitar alterações

         steps:
           - name: Checkout repository
             uses: actions/checkout@v4
             with:
               ref: main # Substitua por 'master' ou outra branch se necessário
               fetch-depth: 0 # Clona todo o histórico
               path: . # Garante que o repositório seja clonado na raiz

           - name: Debug - Verify working directory
             run: |
               echo "Diretório atual:"
               pwd
               echo "Listando arquivos na raiz:"
               ls -la
               echo "Buscando arquivos recursivamente:"
               find . -type f
               echo "Conteúdo do diretório .github/scripts:"
               ls -la .github/scripts || echo "Diretório .github/scripts não encontrado"

           - name: Check required files
             run: |
               if [ ! -f requirements.txt ]; then
                 echo "requirements.txt não encontrado"
                 exit 1
               fi
               if [ ! -f .github/scripts/fetch_latest_video.py ]; then
                 echo "fetch_latest_video.py não encontrado"
                 exit 1
               fi
               if [ ! -f latest-video.js ]; then
                 echo "latest-video.js não encontrado"
                 exit 1
               fi

           - name: Set up Python
             uses: actions/setup-python@v5
             with:
               python-version: '3.11'

           - name: Cache pip
             uses: actions/cache@v4
             with:
               path: ~/.cache/pip
               key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
               restore-keys: |
                 ${{ runner.os }}-pip-

           - name: Install dependencies
             run: |
               python -m pip install --upgrade pip
               pip install -r requirements.txt

           - name: Create or update latest-video.js
             run: |
               python .github/scripts/fetch_latest_video.py
             env:
               CHANNEL_ID: UCWl8Ma619mTTXoo9P7mASdQ

           - name: Commit changes
             run: |
               git config user.name "GitHub Action"
               git config user.email "action@github.com"
               git add latest-video.js
               if [ -n "$(git status --porcelain)" ]; then
                 git pull --rebase
                 git commit -m "Atualiza URL do vídeo mais recente do YouTube"
                 git push
               else
                 echo "Nenhuma alteração no latest-video.js, pulando commit"
               fi
